# Generated by Django 4.1.10 on 2023-08-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlink',
            name='is_for_hire',
            field=models.BooleanField(default=False, verbose_name='For hire'),
        ),
        migrations.AlterField(
            model_name='contactlink',
            name='icon_name',
            field=models.CharField(max_length=50, verbose_name='Icon name'),
        ),
        migrations.AlterField(
            model_name='contactlink',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contactlink',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
